version: "3"

services:
  consul-dev:
    image: consul:latest
    container_name: "consul-dev"
    hostname: consul-dev
    networks:
     - consul-net
    ports:
     - "8500:8500"
     - "8600:8600/udp"
    command: consul agent -dev -client=0.0.0.0

  consul-template:
    image: hashicorp/consul-template:alpine
    container_name: "consul-template"
    hostname: consul-template
    networks:
     - consul-net
    volumes:
     - "./consul-template.hcl:/data/consul-template.hcl:ro"
     - "./src/config:/config"
    command: consul-template -config /data/consul-template.hcl

networks:
  consul-net: